# Generated by Django 5.2.1 on 2025-05-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('shop_name', models.CharField(max_length=100)),
                ('product_specialty', models.CharField(max_length=50)),
                ('price_range_low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_range_high', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('accepting_custom_orders', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.inventory')),
            ],
        ),
    ]
