# Generated by Django 5.2.1 on 2025-06-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='price_range_high',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='price_range_low',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='product_specialty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
