# Generated by Django 5.2.1 on 2025-06-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
