# Generated by Django 5.2.2 on 2025-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_description_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageurl',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
