# Generated by Django 5.2.3 on 2025-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
