# Generated by Django 5.2.3 on 2025-06-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_imageurl_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='slug',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
