# Generated by Django 5.2.3 on 2025-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_artisan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
