# Generated by Django 5.2.3 on 2025-06-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
    ]
