# Generated by Django 5.2.3 on 2025-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
