# Generated by Django 5.2.3 on 2025-07-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
