# Generated by Django 5.2.3 on 2025-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_artisan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
