# Generated by Django 5.2.3 on 2025-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
