# Generated by Django 5.2.3 on 2025-07-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
    ]
