# Generated by Django 5.2.3 on 2025-07-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_product_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
