# Generated by Django 5.2.3 on 2025-07-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_sentence_draw', models.CharField(max_length=50)),
                ('hero_header_draw', models.CharField(max_length=25)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.artisan')),
            ],
        ),
    ]
