# Generated by Django 5.2.3 on 2025-08-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_textcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artisan',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
