# Generated by Django 5.2.3 on 2025-08-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_artisan_full_name_artisan_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='shop', max_length=50)),
                ('shop_description', models.CharField(default='', max_length=250)),
                ('accepting_custom_orders', models.BooleanField(default=False)),
                ('maximum_active_orders', models.IntegerField(default=1000)),
                ('standard_processing_days', models.IntegerField(default=10)),
                ('shop_location', models.CharField(default='', max_length=100)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('cad', 'CAD')], default='usd', max_length=3)),
                ('shop_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('vacation', 'Vacation'), ('construction', 'Construction')], default='active', max_length=30)),
                ('status_message', models.CharField(default='', max_length=250)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_policy', models.CharField(default='', max_length=500)),
                ('return_policy', models.CharField(default='', max_length=500)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.artisan')),
            ],
        ),
    ]
