# Generated by Django 5.2.3 on 2025-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_shopsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='image',
            field=models.ImageField(default='', upload_to='pfps/'),
        ),
    ]
