# Generated by Django 5.2.3 on 2025-09-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_artisan_facebook_link_artisan_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='custom_order_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='gallery_subtext',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='project_description_placeholder',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
