# Generated by Django 5.2.3 on 2025-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_textcontent_custom_order_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
