# Generated by Django 5.2.3 on 2025-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_artisan_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
