# Generated by Django 5.2.3 on 2025-09-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_artisan_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
