# Generated by Django 5.2.3 on 2025-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_shopsettings_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='terms_and_conditions',
            field=models.CharField(default='', max_length=500),
        ),
    ]
