# Generated by Django 5.2.3 on 2025-09-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_shopsettings_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='terms_and_conditions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
