# Generated by Django 5.2.3 on 2025-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_artisan_options_remove_artisan_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
