# Generated by Django 5.2.3 on 2025-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_artisan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='troute_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='troute_login',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
