# Generated by Django 5.2.3 on 2025-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_artisan_troute_key_artisan_troute_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='troute_unique_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
