# Generated by Django 4.2.25 on 2025-10-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_artisan_managers_artisan_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='hero_header_draw',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='hero_sentence_draw',
            field=models.CharField(max_length=100),
        ),
    ]
