# Generated by Django 5.2.3 on 2025-11-04 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.CharField(default='', max_length=1000)),
                ('shipping_policy', models.CharField(default='', max_length=500)),
                ('return_policy', models.CharField(default='', max_length=500)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
