# Generated by Django 5.2.3 on 2025-11-04 16:48

from django.db import migrations

def move_policies_data(apps, schema_editor):
    ShopSettings = apps.get_model("core", "ShopSettings")
    Policies = apps.get_model("core", "Policies")

    for shop in ShopSettings.objects.all():
        Policies.objects.update_or_create(
            artisan=shop.artisan,
            defaults={
                "terms_and_conditions": shop.terms_and_conditions,
                "shipping_policy": shop.shipping_policy,
                "return_policy": shop.return_policy,
            },
        )

def reverse_move_policies_data(apps, schema_editor):
    ShopSettings = apps.get_model("core", "ShopSettings")
    Policies = apps.get_model("core", "Policies")

    for policy in Policies.objects.all():
        shop, _ = ShopSettings.objects.get_or_create(artisan=policy.artisan)
        shop.terms_and_conditions = policy.terms_and_conditions
        shop.shipping_policy = policy.shipping_policy
        shop.return_policy = policy.return_policy
        shop.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_policies'),
    ]

    operations = [
        migrations.RunPython(move_policies_data, reverse_move_policies_data),
    ]
