# Generated by Django 5.2.3 on 2025-11-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_migrate_shopsettings_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='shipping_policy',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='terms_and_conditions',
        ),
    ]
