# Generated by Django 5.2.3 on 2025-11-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_shopsettings_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='text_color_secondary',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
