# Generated by Django 5.2.3 on 2025-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_theme_text_color_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='ttl',
            field=models.PositiveIntegerField(default=60000),
        ),
    ]
