# Generated by Django 5.2.3 on 2025-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_theme_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='ttl',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
