# Generated by Django 5.2.3 on 2025-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_theme_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='return_policy',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='policies',
            name='shipping_policy',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='policies',
            name='terms_and_conditions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
