# Generated by Django 5.2.3 on 2025-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_policies_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='ttl',
            field=models.PositiveIntegerField(default=60000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ttl',
            field=models.PositiveIntegerField(default=60000),
        ),
    ]
