# Generated by Django 5.2.3 on 2025-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_textcontent_ttl_alter_theme_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='ttl',
            field=models.PositiveIntegerField(default=60000),
        ),
    ]
