# Generated by Django 4.2.26 on 2025-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='troute_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policies',
            name='ttl',
            field=models.PositiveIntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ttl',
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
