# Generated by Django 4.2.26 on 2025-12-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='payment',
            name='processing_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
