# Generated by Django 4.2.26 on 2025-12-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_rename_amount_payment_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default=''),
        ),
    ]
