# Generated by Django 4.2.26 on 2025-12-16 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='artisan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
