# Generated by Django 4.2.26 on 2025-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_payment_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
