# Generated by Django 4.2.26 on 2025-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_payment_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transtype',
            field=models.CharField(default='AUTH_CAPTURE'),
        ),
    ]
