# Generated by Django 4.2.26 on 2025-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_payment_transtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='image',
            field=models.ImageField(blank=True, upload_to='pfps/'),
        ),
    ]
