# Generated by Django 4.2.26 on 2025-12-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_artisan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='featured_header',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='featured_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='hero_header_draw',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='hero_sentence_draw',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
