# Generated by Django 4.2.26 on 2026-01-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_textcontent_featured_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('in_progress', 'In_Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='featured_header',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
