# Generated by Django 4.2.26 on 2026-01-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_order_status_alter_textcontent_featured_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
