# Generated by Django 4.2.26 on 2026-01-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_orderitems_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out of stock', 'Out of Stock')], default='active', max_length=20),
        ),
    ]
