# Generated by Django 4.2.26 on 2026-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='cap_maximum_orders',
            field=models.BooleanField(default=False),
        ),
    ]
