# Generated by Django 4.2.26 on 2026-02-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_shopsettings_cap_maximum_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textcontent',
            old_name='hero_sentence_draw',
            new_name='hero_sentence',
        ),
        migrations.RenameField(
            model_name='textcontent',
            old_name='hero_header_draw',
            new_name='hero_title',
        ),
    ]
