# Generated by Django 4.2.26 on 2026-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_rename_hero_sentence_draw_textcontent_hero_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='hero_sentence',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
