# Generated by Django 4.2.26 on 2026-02-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_textcontent_hero_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='ttl',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
