# Generated by Django 4.2.26 on 2026-02-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_product_stocked_alter_policies_ttl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stocked',
            new_name='track_stock',
        ),
    ]
